import fs from 'node:fs';
import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
import { globalKpi, hours } from '../src/metrics.js';

const base = process.env.QA_URL || 'http://127.0.0.1:3020';
fs.mkdirSync('screenshots', { recursive: true });
const source = JSON.parse(fs.readFileSync('public/data/metrics.json', 'utf8'));
const locations = JSON.parse(fs.readFileSync('public/data/locations.json', 'utf8'));
const browser = await chromium.launch({ channel: process.env.PW_CHANNEL || 'chrome' });
const results = [];
const failures = [];
const check = (name, value) => { assert(value, name); results.push({ name, passed: true }); console.log('PASS ' + name); };
try {
  for (const width of [1440, 390]) {
    const page = await browser.newPage({ viewport: { width, height: 1000 } });
    page.on('pageerror', error => failures.push(error.message));
    await page.goto(base);
    await page.locator('.hub-row').first().waitFor();
    check(`${width}: all eight list items`, await page.locator('.hub-row').count() === 8);
    check(`${width}: all eight markers`, await page.locator('.leaflet-marker-icon').count() === 8);
    check(`${width}: weighted global mean`, await page.locator('[data-kpi="Global Mean Dwell Time"]').textContent() === hours(globalKpi(source.hubs).mean_dwell_hours));
    check(`${width}: no overflow`, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    const list = await page.locator('.hub-list').boundingBox();
    const map = await page.locator('.map-region').boundingBox();
    check(`${width}: layout`, width === 1440 ? map.x > list.x + list.width : map.y > list.y);
    await page.locator('.leaflet-tile-loaded').first().waitFor({ timeout: 30000 });
    check(`${width}: real map tiles and attribution`, await page.locator('.leaflet-tile-loaded').count() > 0 && await page.getByText('OpenStreetMap', { exact: false }).count() > 0);
    await page.screenshot({ path: `screenshots/${width === 1440 ? 'desktop' : 'mobile'}.png`, fullPage: true });
    await page.getByLabel('Priority Only', { exact: true }).check();
    check(`${width}: shared priority list/map`, await page.locator('.hub-row').count() === 5 && await page.locator('.leaflet-marker-icon').count() === 5);
    await page.getByLabel('Cari hub atau kota').fill('Makassar');
    check(`${width}: combined search and priority`, await page.locator('.hub-row').count() === 1 && await page.locator('.leaflet-marker-icon').count() === 1);
    await page.getByRole('button', { name: 'Detail Hub Makassar', exact: true }).click();
    check(`${width}: correct detail metrics`, await page.getByRole('dialog').getByText('350', { exact: true }).count() === 1 && await page.getByRole('dialog').getByText('11,17 jam', { exact: true }).count() === 2);
    await page.screenshot({ path: `screenshots/detail-${width}.png`, fullPage: true });
    await page.keyboard.press('Escape');
    check(`${width}: escape closes and restores focus`, await page.getByRole('dialog').count() === 0 && await page.getByRole('button', { name: 'Detail Hub Makassar', exact: true }).evaluate(element => element === document.activeElement));
    await page.getByLabel('Cari hub atau kota').fill('not-a-real-hub');
    await page.getByText('Hub tidak ditemukan', { exact: true }).waitFor();
    check(`${width}: shared empty state`, await page.locator('.hub-row').count() === 0 && await page.locator('.leaflet-marker-icon').count() === 0);
    await page.screenshot({ path: `screenshots/empty-${width}.png`, fullPage: true });
    await page.getByRole('button', { name: 'Reset filter', exact: true }).click();
    await page.locator('.leaflet-marker-icon').first().click();
    await page.locator('.leaflet-popup').waitFor();
    check(`${width}: marker popup contains metrics`, (await page.locator('.map-popup').textContent()).includes('Completed visits:'));
    await page.locator('.map-popup button').click();
    await page.getByRole('dialog').waitFor();
    await page.getByRole('button', { name: 'Tutup detail hub' }).click();
    check(`${width}: marker opens and closes detail`, await page.getByRole('dialog').count() === 0);
    await page.close();
  }
  const loading = await browser.newPage();
  await loading.route('**/data/*.json', async route => { await new Promise(resolve => setTimeout(resolve, 1200)); await route.continue(); });
  await loading.goto(base);
  await loading.getByText('Memuat metrics dan lokasi hub…').waitFor();
  await loading.screenshot({ path: 'screenshots/loading.png' });
  check('visible loading state', true);
  await loading.locator('.hub-row').first().waitFor();
  await loading.close();
  const error = await browser.newPage();
  await error.route('**/data/metrics.json', route => route.fulfill({ status: 503, body: '{}' }));
  await error.goto(base);
  await error.getByRole('alert').waitFor();
  await error.screenshot({ path: 'screenshots/error.png' });
  check('network error state', true);
  await error.unroute('**/data/metrics.json');
  await error.getByRole('button', { name: 'Coba lagi' }).click();
  await error.locator('.hub-row').first().waitFor();
  check('retry recovers data', true);
  await error.close();
  const empty = await browser.newPage();
  await empty.route('**/data/metrics.json', route => route.fulfill({json:{...source,hubs:[]}}));
  await empty.route('**/data/locations.json', route => route.fulfill({json:{...locations,hubs:[]}}));
  await empty.goto(base);
  await empty.getByText('Hub tidak ditemukan',{exact:true}).waitFor();
  check('empty dataset without fake mean', await empty.locator('[data-kpi="Global Mean Dwell Time"]').textContent() === 'Tidak tersedia');
  await empty.close();
  const injection = await browser.newPage();
  const hostile = structuredClone(source);
  hostile.hubs[0].hub_name = '<img src=x onerror="window.injected=true">';
  await injection.route('**/data/metrics.json', route => route.fulfill({json:hostile}));
  await injection.goto(base);
  await injection.locator('.hub-row').first().waitFor();
  check('untrusted name rendered as inert text', !(await injection.evaluate(()=>Boolean(window.injected))) && await injection.locator('.hub-list img').count() === 0);
  await injection.close();
  const reduced = await browser.newPage({ reducedMotion: 'reduce' });
  await reduced.goto(base);
  await reduced.locator('.hub-row').first().waitFor();
  await reduced.keyboard.press('Tab');
  check('keyboard skip link', await reduced.locator('.skip-link').evaluate(element => element === document.activeElement));
  await reduced.getByLabel('Cari hub atau kota').focus();
  check('keyboard input focus', await reduced.getByLabel('Cari hub atau kota').evaluate(element => element === document.activeElement));
  check('reduced motion preference respected', await reduced.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches));
  await reduced.close();
  check('no browser runtime errors', failures.length === 0);
} finally {
  fs.mkdirSync('docs/testing', { recursive: true });
  fs.writeFileSync('docs/testing/browser-results.json', JSON.stringify({base,results,runtime_errors:failures},null,2)+'\n');
  await browser.close();
}
