import Link from '@/frontend/compat/Link';
import { useParams, useSearchParams } from 'react-router-dom';
import { CalendarClock, MapPin, ShieldAlert } from 'lucide-react';
import { useState } from 'react';
import { SiteHeader } from '@/components/ui/site-header';
import { PageHeader } from '@/components/ui/page-header';
import { SellerDashboard } from '@/components/tracking/seller-dashboard';
import { SellerTicketForm } from '@/components/tracking/seller-ticket-form';
import { JourneyMapDisclosure } from '@/components/tracking/journey-map-disclosure';
import { buildJourney } from '@/lib/tracking/journey';
import type { SellerShipment } from '@/lib/tracking/types';
import { post, useAuth, useData } from '../api';

type Shipment = SellerShipment & { origin_city: string | null; risk_status: 'on_track' | 'at_risk' | 'action_required' | 'resolved' };
type Detail = { shipment: Shipment; events: Array<{ id: string; status_label: string; description: string; location: string; occurred_at: string }>; resolutions: Array<{ id: string; resolution_type: string; status: string; submitted_at: string }>; tickets: Array<{ id: string; ticket_number: string; status: string; customer_note: string | null; created_at: string }> };
type Ticket = { id: string; shipment_id: string; ticket_number: string; status: string; customer_note: string | null; proof_available?: boolean; shipments: { tracking_number: string; destination_city: string | null } | null };

function Header() { const { user } = useAuth(); return <SiteHeader userName={user?.name || user?.email || ''} role={user?.role || 'consumer'} />; }
function Loading({ error, loading }: { error: string; loading: boolean }) { return loading ? <p role="status" className="text-sm text-muted-foreground">Memuat data…</p> : error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null; }
function date(value?: string | null) { if (!value) return '—'; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? '—' : new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(parsed); }
function riskLabel(value: string) { return value === 'action_required' ? 'Perlu tindakan' : value === 'at_risk' ? 'Berisiko' : value === 'resolved' ? 'Ditangani' : 'Sesuai jadwal'; }

export function ConsumerPage() {
  const state = useData<{ shipments: Shipment[] }>('/api/v1/view/consumer');
  return <><Header /><main id="main-content" className="app-main space-y-7"><PageHeader eyebrow="Ruang Konsumen" title="Paket saya" description="Kiriman yang terhubung dengan akunmu, beserta posisi terakhir dan tindakan yang diperlukan. Untuk detail, masukkan kode akses dari pesan pengiriman." /><Loading {...state} />{state.data && (state.data.shipments.length ? <section aria-label="Daftar paket saya" className="grid gap-3">{state.data.shipments.map((item) => <article className="surface-flat flex flex-wrap items-center justify-between gap-4 p-5" key={item.tracking_number}><div><p className="text-xs font-semibold text-muted-foreground">{item.service_type.replace('_', ' ')} · {item.origin_city} → {item.destination_city}</p><h2 className="mt-1 text-lg font-bold">{item.tracking_number}</h2><p className="mt-2 text-sm">{riskLabel(item.risk_status)} · {item.current_location || 'Lokasi belum tersedia'}</p>{item.exception_reason && <p className="mt-1 text-sm text-muted-foreground">{item.exception_reason}</p>}</div><Link href={`/lacak?resi=${encodeURIComponent(item.tracking_number)}`} className="text-sm font-semibold text-primary underline">Lacak dengan kode akses →</Link></article>)}</section> : <section className="surface-flat p-7"><h2 className="section-title">Belum ada paket terhubung</h2><p className="mt-2 text-sm text-muted-foreground">Gunakan pencarian publik dengan resi dan kode akses enam digit.</p><Link href="/lacak" className="mt-5 inline-block font-semibold text-primary">Lacak dengan resi →</Link></section>)}<p className="text-xs text-muted-foreground">Memiliki kode aktivasi petugas? <Link href="/aktivasi-admin" className="underline">Aktivasi Admin</Link>.</p></main></>;
}

export function SellerPage() {
  const state = useData<{ shipments: Shipment[]; settlementCount: number }>('/api/v1/view/seller');
  const shipments = state.data?.shipments || [];
  const urgent = shipments.filter((item) => item.risk_status === 'action_required');
  return <><Header /><main id="main-content" className="app-main space-y-7"><PageHeader eyebrow="Ruang Seller" title="Kiriman dan arus dana" description="Lihat pesanan toko yang perlu ditindaklanjuti, lalu cocokkan settlement dengan mutasi bank." /><Loading {...state} />{state.data && <><section aria-label="Ringkasan Seller" className="grid gap-3 sm:grid-cols-3">{[['Kiriman aktif', shipments.length], ['Perlu tindakan', urgent.length], ['Settlement tercatat', state.data.settlementCount]].map(([label, value]) => <article key={label} className="surface-flat p-5"><h2 className="text-xs font-semibold text-muted-foreground">{label}</h2><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</section><section className="grid gap-4 md:grid-cols-2"><article className="surface-flat p-6"><h2 className="section-title">Pengiriman toko</h2><p className="mt-2 text-sm text-muted-foreground">Pantau kiriman milik akun ini, filter risiko, dan ekspor daftar.</p><Link href="/pengiriman" className="mt-5 inline-block font-semibold text-primary underline">Buka pengiriman →</Link></article><article className="surface-flat p-6"><h2 className="section-title">Rekonsiliasi bank</h2><p className="mt-2 text-sm text-muted-foreground">Tinjau mutasi sebelum menyimpan transaksi.</p><Link href="/import" className="mt-5 inline-block font-semibold text-primary underline">Buka rekonsiliasi →</Link></article></section>{urgent.length > 0 && <section className="surface-flat p-6"><h2 className="section-title">Perlu ditindaklanjuti</h2><ul className="mt-4 divide-y">{urgent.slice(0, 5).map((item) => <li key={item.id} className="flex justify-between gap-3 py-3"><span><strong>{item.tracking_number}</strong> · {item.destination_city}</span><Link href={`/pengiriman/${item.tracking_number}`} className="text-primary">Lihat detail</Link></li>)}</ul></section>}</>}</main></>;
}

export function SellerShipmentsPage() {
  const state = useData<{ shipments: SellerShipment[] }>('/api/v1/view/seller-shipments');
  return <><Header /><main id="main-content" className="app-main overflow-x-clip"><PageHeader eyebrow="Control tower" title="Operasi pengiriman" description="Prioritaskan kiriman yang membutuhkan perhatian. Risiko, konteks, dan tindakan tersedia dalam satu tampilan." /><Loading {...state} />{state.data && <SellerDashboard shipments={state.data.shipments} />}</main></>;
}

export function SellerShipmentPage() {
  const { awb = '' } = useParams();
  const state = useData<Detail>(`/api/v1/view/seller/shipment/${encodeURIComponent(awb)}`);
  const shipment = state.data?.shipment;
  const journey = shipment ? buildJourney(shipment) : null;
  return <><Header /><main id="main-content" className="app-main max-w-5xl"><Link href="/pengiriman" className="text-sm font-semibold text-primary">← Kembali ke pengiriman</Link><Loading {...state} />{shipment && <><section className="mt-5 rounded-2xl bg-[#2a2026] p-6 text-white sm:p-8"><p className="eyebrow">Detail operasional</p><h1 className="mt-3 text-3xl font-bold">{shipment.tracking_number}</h1><p className="mt-2 text-sm text-white/65">{shipment.origin_city} → {shipment.destination_city}</p><p className="mt-3 text-sm">{riskLabel(shipment.risk_status)}</p></section><section className="mt-5 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><section className="surface p-6"><h2 className="section-title">Timeline</h2><ol className="mt-6 space-y-6">{state.data!.events.map((event) => <li key={event.id} className="flex gap-3"><MapPin className="size-5 shrink-0 text-primary" /><article><h3 className="text-sm font-bold">{event.status_label}</h3><p className="mt-1 text-sm text-muted-foreground">{event.description}</p><p className="mt-1 text-xs text-muted-foreground">{event.location} · {date(event.occurred_at)}</p></article></li>)}</ol></section><aside className="space-y-5"><section className="surface p-5"><h2 className="section-title">Konteks kendala</h2><p className="mt-4 flex gap-3 text-sm"><ShieldAlert className="size-5 text-primary" />{shipment.exception_reason || 'Tidak ada kendala aktif.'}</p><p className="mt-4 flex gap-3 text-sm"><CalendarClock className="size-5 text-primary" />Estimasi tiba {date(shipment.estimated_delivery_at)}</p></section><section className="surface p-5"><h2 className="section-title">Tindak lanjut</h2><p className="mt-3 text-sm">{state.data!.resolutions.length} instruksi · {state.data!.tickets.length} tiket CS</p></section></aside></section>{journey && <JourneyMapDisclosure journey={journey} />}<SellerTicketForm awb={shipment.tracking_number} /></>}</main></>;
}

export function AdminPage() {
  const state = useData<{ shipments: Shipment[] }>('/api/v1/view/admin');
  const rows = state.data?.shipments || [];
  const urgent = rows.filter((item) => item.risk_status === 'action_required');
  const risk = rows.filter((item) => item.risk_status === 'at_risk');
  return <><Header /><main id="main-content" className="app-main space-y-7"><PageHeader eyebrow="Operasi Anteraja" title="Pusat operasi" description="Semua kiriman aktif yang membutuhkan perhatian, melintasi akun Seller." /><Loading {...state} />{state.data && <><section aria-label="Ringkasan operasi" className="grid gap-3 sm:grid-cols-3">{[['Aktif', rows.length, 'bg-[#d5efe0] text-[#19543a]'], ['Perlu tindakan', urgent.length, 'bg-[#f9d6df] text-[#85132c]'], ['Berisiko', risk.length, 'bg-[#ffe8ab] text-[#713d06]']].map(([label, value, tone]) => <article key={label} className={`rounded-xl p-5 ${tone}`}><h2 className="text-xs font-semibold">{label}</h2><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</section><section className="surface-flat overflow-hidden"><header className="border-b px-5 py-4"><h2 className="section-title">Tangani lebih dulu</h2><p className="mt-1 text-sm text-muted-foreground">Prioritas dari kendala dan estimasi tiba. <Link href="/admin/kiriman" className="text-primary underline">Lihat semua kiriman →</Link></p></header><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Resi</th><th>Tujuan</th><th>Posisi terakhir</th><th>Kendala</th><th>Estimasi</th></tr></thead><tbody>{[...urgent.slice(0, 12), ...risk.slice(0, 8)].map((item) => <tr key={item.id}><td><Link href={`/admin/pengiriman/${item.id}`} className="font-semibold text-primary">{item.tracking_number}</Link></td><td>{item.destination_city || '—'}</td><td>{item.current_location || '—'}</td><td><strong>{riskLabel(item.risk_status)}</strong><p className="text-xs text-muted-foreground">{item.exception_reason || 'Perlu ditinjau'}</p></td><td>{date(item.estimated_delivery_at)}</td></tr>)}{!urgent.length && !risk.length && <tr><td colSpan={5} className="py-10 text-center">Tidak ada kiriman yang perlu ditangani.</td></tr>}</tbody></table></div></section></>}</main></>;
}

export function AdminShipmentsPage() {
  const [params, setParams] = useSearchParams();
  const path = `/api/v1/view/admin-shipments?${params.toString()}`;
  const state = useData<{ shipments: Shipment[]; count: number; page: number }>(path);
  const [search, setSearch] = useState(params.get('q') || '');
  const [risk, setRisk] = useState(params.get('risiko') || 'all');
  return <><Header /><main id="main-content" className="app-main space-y-6"><PageHeader eyebrow="Operasi Anteraja" title="Semua kiriman" description="Cari resi, penerima, atau kota. Hanya petugas Admin yang dapat membaca daftar lintas Seller." /><form onSubmit={(event) => { event.preventDefault(); setParams({ q: search, risiko: risk, halaman: '1' }); }} className="surface-flat flex flex-wrap items-end gap-3 p-4"><label className="grid min-w-56 flex-1 gap-1 text-sm font-semibold">Cari kiriman<input value={search} onChange={(event) => setSearch(event.target.value)} maxLength={40} placeholder="Resi, penerima, kota" className="h-10 rounded-md border bg-white px-3 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Risiko<select value={risk} onChange={(event) => setRisk(event.target.value)} className="h-10 rounded-md border bg-white px-3 font-normal">{[['all', 'Semua risiko'], ['action_required', 'Perlu tindakan'], ['at_risk', 'Berisiko'], ['on_track', 'Sesuai jadwal'], ['resolved', 'Ditangani']].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button type="submit" className="h-10 rounded-md bg-primary px-4 text-sm font-semibold text-white">Terapkan</button></form><Loading {...state} />{state.data && <section className="surface-flat overflow-hidden"><div className="border-b px-5 py-3 text-sm text-muted-foreground">{state.data.count} kiriman ditemukan · halaman {state.data.page}</div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Resi</th><th>Penerima</th><th>Tujuan</th><th>Status</th><th>Posisi terakhir</th></tr></thead><tbody>{state.data.shipments.map((item) => <tr key={item.id}><td><Link href={`/admin/pengiriman/${item.id}`} className="font-semibold text-primary">{item.tracking_number}</Link></td><td>{item.recipient_name || '—'}</td><td>{item.destination_city || '—'}</td><td>{riskLabel(item.risk_status)}</td><td>{item.current_location || '—'}</td></tr>)}{!state.data.shipments.length && <tr><td colSpan={5} className="py-10 text-center">Tidak ada kiriman yang sesuai.</td></tr>}</tbody></table></div><nav className="flex justify-between border-t px-5 py-4">{state.data.page > 1 ? <button onClick={() => setParams({ q: search, risiko: risk, halaman: String(state.data!.page - 1) })} className="text-primary">← Sebelumnya</button> : <span />}{state.data.page * 25 < state.data.count && <button onClick={() => setParams({ q: search, risiko: risk, halaman: String(state.data!.page + 1) })} className="text-primary">Berikutnya →</button>}</nav></section>}</main></>;
}

export function AdminShipmentPage() {
  const { awb = '' } = useParams();
  const state = useData<Detail>(`/api/v1/view/admin/shipment/${encodeURIComponent(awb)}`);
  const shipment = state.data?.shipment;
  return <><Header /><main id="main-content" className="app-main max-w-5xl space-y-6"><Link href="/admin/kiriman" className="text-sm font-semibold text-primary">← Semua kiriman</Link><Loading {...state} />{shipment && <><header className="surface-flat p-6"><p className="eyebrow">Detail operasional</p><h1 className="page-title">{shipment.tracking_number}</h1><p className="page-copy">{shipment.origin_city || 'Asal belum tersedia'} → {shipment.destination_city || 'Tujuan belum tersedia'}</p><dl className="mt-5 grid gap-4 border-t pt-5 sm:grid-cols-3"><div><dt className="text-xs text-muted-foreground">Risiko</dt><dd className="font-semibold">{riskLabel(shipment.risk_status)}</dd></div><div><dt className="text-xs text-muted-foreground">Posisi terakhir</dt><dd className="font-semibold">{shipment.current_location || '—'}</dd></div><div><dt className="text-xs text-muted-foreground">Estimasi tiba</dt><dd className="font-semibold">{date(shipment.estimated_delivery_at)}</dd></div></dl></header>{shipment.exception_reason && <section className="surface-flat p-6"><h2 className="section-title">Kendala yang diketahui</h2><p className="mt-2">{shipment.exception_reason}</p></section>}<section className="grid gap-5 lg:grid-cols-2"><article className="surface-flat p-6"><h2 className="section-title">Riwayat perjalanan</h2><ol className="mt-4 divide-y">{state.data!.events.map((item) => <li key={item.id} className="py-3"><h3 className="font-semibold">{item.status_label}</h3><p className="text-sm text-muted-foreground">{item.description}</p><p className="text-xs text-muted-foreground">{item.location} · {date(item.occurred_at)}</p></li>)}</ol></article><div className="space-y-5"><article className="surface-flat p-6"><h2 className="section-title">Instruksi penerima</h2><ul className="mt-4 divide-y">{state.data!.resolutions.map((item) => <li key={item.id} className="py-3 text-sm">{item.resolution_type.replaceAll('_', ' ')} · {item.status} · {date(item.submitted_at)}</li>)}</ul></article><article className="surface-flat p-6"><h2 className="section-title">Tiket CS</h2><ul className="mt-4 divide-y">{state.data!.tickets.map((item) => <li key={item.id} className="py-3 text-sm"><strong>{item.ticket_number}</strong> · {item.status}<p>{item.customer_note || 'Tidak ada catatan tambahan.'}</p></li>)}</ul></article></div></section></>}</main></>;
}

export function AdminTicketsPage() {
  const state = useData<{ tickets: Ticket[] }>('/api/v1/view/tickets');
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');
  async function change(ticket: Ticket) {
    const status = ticket.status === 'open' ? 'in_progress' : 'resolved';
    setBusy(ticket.id); setError('');
    try { await post('/api/v1/admin/assistant/action', { ticketId: ticket.id, status }); state.reload(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'Status tiket belum berubah.'); }
    finally { setBusy(''); }
  }
  return <><Header /><main id="main-content" className="app-main space-y-6"><PageHeader eyebrow="Customer service" title="Tiket pengiriman" description="Lihat konteks resi sebelum mengambil alih kasus. Perubahan status dicatat bersama identitas petugas." /><Loading {...state} />{error && <p role="alert" className="text-destructive">{error}</p>}{state.data && (state.data.tickets.length ? <section className="surface-flat overflow-hidden"><div className="hidden grid-cols-[1.1fr_1fr_1.6fr_1fr_auto] gap-4 border-b px-5 py-3 text-xs font-semibold lg:grid"><span>Tiket</span><span>Kiriman</span><span>Catatan penerima</span><span>Status</span><span>Tindakan</span></div><ul className="divide-y">{state.data.tickets.map((ticket) => <li key={ticket.id} id={`ticket-${ticket.id}`} className="grid scroll-mt-28 gap-4 p-5 lg:grid-cols-[1.1fr_1fr_1.6fr_1fr_auto] lg:items-center"><strong>{ticket.ticket_number}</strong><div><Link href={`/admin/pengiriman/${ticket.shipment_id}`} className="text-primary">{ticket.shipments?.tracking_number || 'Lihat kiriman'}</Link><p className="text-xs text-muted-foreground">{ticket.shipments?.destination_city}</p></div><p className="break-words text-sm text-muted-foreground">{ticket.customer_note || 'Tidak ada catatan tambahan.'}{ticket.proof_available ? <a href={`/api/v1/admin/tickets/${ticket.id}/proof`} className="mt-2 block font-semibold text-primary underline underline-offset-2">Unduh foto bukti</a> : null}</p><span className="text-sm font-semibold">{ticket.status === 'open' ? 'Baru' : ticket.status === 'in_progress' ? 'Sedang ditangani' : ticket.status === 'resolved' ? 'Selesai' : 'Ditutup'}</span>{['open', 'in_progress'].includes(ticket.status) ? <button disabled={busy === ticket.id} onClick={() => void change(ticket)} className="rounded-md border px-3 py-2 text-sm font-semibold">{busy === ticket.id ? 'Menyimpan…' : ticket.status === 'open' ? 'Mulai tangani' : 'Tandai selesai'}</button> : <span className="text-sm text-muted-foreground">—</span>}</li>)}</ul></section> : <section className="surface-flat p-7"><h2 className="section-title">Belum ada tiket CS</h2></section>)}</main></>;
}
